export default {
    categories: [
        {
            name: "Basic Operations",
            symbols: [
                { symbol: "×", name: "multiply" },
                { symbol: "÷", name: "divide" },
                { symbol: "±", name: "plus-minus" },
                { symbol: "∓", name: "minus-plus" },
                { symbol: "·", name: "dot" },
                { symbol: "√", name: "sqrt" },
                { symbol: "∛", name: "cube root" },
                { symbol: "∜", name: "4th root" },
            ],
        },
        {
            name: "Comparison",
            symbols: [
                { symbol: "≤", name: "less or equal" },
                { symbol: "≥", name: "greater or equal" },
                { symbol: "≠", name: "not equal" },
                { symbol: "≈", name: "approx" },
                { symbol: "≡", name: "identical" },
                { symbol: "≢", name: "not identical" },
                { symbol: "≪", name: "much less" },
                { symbol: "≫", name: "much greater" },
                { symbol: "∝", name: "proportional" },
            ],
        },
        {
            name: "Set Theory",
            symbols: [
                { symbol: "∈", name: "element of" },
                { symbol: "∉", name: "not element" },
                { symbol: "⊂", name: "subset" },
                { symbol: "⊃", name: "superset" },
                { symbol: "⊆", name: "subset or eq" },
                { symbol: "⊇", name: "superset or eq" },
                { symbol: "∪", name: "union" },
                { symbol: "∩", name: "intersection" },
                { symbol: "∅", name: "empty set" },
            ],
        },
        {
            name: "Logic",
            symbols: [
                { symbol: "∧", name: "and" },
                { symbol: "∨", name: "or" },
                { symbol: "¬", name: "not" },
                { symbol: "⊕", name: "xor" },
                { symbol: "→", name: "implies" },
                { symbol: "←", name: "implied by" },
                { symbol: "↔", name: "iff" },
                { symbol: "∀", name: "for all" },
                { symbol: "∃", name: "exists" },
                { symbol: "∄", name: "not exists" },
                { symbol: "∴", name: "therefore" },
                { symbol: "∵", name: "because" },
            ],
        },
        {
            name: "Calculus & Analysis",
            symbols: [
                { symbol: "∫", name: "integral" },
                { symbol: "∬", name: "double int" },
                { symbol: "∭", name: "triple int" },
                { symbol: "∮", name: "contour int" },
                { symbol: "∂", name: "partial" },
                { symbol: "∇", name: "nabla" },
                { symbol: "∑", name: "sum" },
                { symbol: "∏", name: "product" },
                { symbol: "∞", name: "infinity" },
                { symbol: "lim", name: "limit" },
            ],
        },
        {
            name: "Greek Letters",
            symbols: [
                { symbol: "α", name: "alpha" },
                { symbol: "β", name: "beta" },
                { symbol: "γ", name: "gamma" },
                { symbol: "δ", name: "delta" },
                { symbol: "ε", name: "epsilon" },
                { symbol: "θ", name: "theta" },
                { symbol: "λ", name: "lambda" },
                { symbol: "μ", name: "mu" },
                { symbol: "π", name: "pi" },
                { symbol: "σ", name: "sigma" },
                { symbol: "φ", name: "phi" },
                { symbol: "ω", name: "omega" },
                { symbol: "Δ", name: "Delta" },
                { symbol: "Σ", name: "Sigma" },
                { symbol: "Π", name: "Pi" },
                { symbol: "Ω", name: "Omega" },
            ],
        },
        {
            name: "Superscripts & Subscripts",
            symbols: [
                { symbol: "⁰", name: "sup 0" },
                { symbol: "¹", name: "sup 1" },
                { symbol: "²", name: "squared" },
                { symbol: "³", name: "cubed" },
                { symbol: "⁴", name: "sup 4" },
                { symbol: "⁵", name: "sup 5" },
                { symbol: "⁶", name: "sup 6" },
                { symbol: "⁷", name: "sup 7" },
                { symbol: "⁸", name: "sup 8" },
                { symbol: "⁹", name: "sup 9" },
                { symbol: "⁺", name: "sup +" },
                { symbol: "⁻", name: "sup -" },
                { symbol: "ⁿ", name: "sup n" },
                { symbol: "₀", name: "sub 0" },
                { symbol: "₁", name: "sub 1" },
                { symbol: "₂", name: "sub 2" },
            ],
        },
        {
            name: "Fractions",
            symbols: [
                { symbol: "½", name: "1/2" },
                { symbol: "⅓", name: "1/3" },
                { symbol: "⅔", name: "2/3" },
                { symbol: "¼", name: "1/4" },
                { symbol: "¾", name: "3/4" },
                { symbol: "⅕", name: "1/5" },
                { symbol: "⅛", name: "1/8" },
                { symbol: "⅜", name: "3/8" },
            ],
        },
        {
            name: "Geometry & Angles",
            symbols: [
                { symbol: "°", name: "degree" },
                { symbol: "∠", name: "angle" },
                { symbol: "∟", name: "right angle" },
                { symbol: "⊥", name: "perpendicular" },
                { symbol: "∥", name: "parallel" },
                { symbol: "△", name: "triangle" },
                { symbol: "□", name: "square" },
                { symbol: "○", name: "circle" },
            ],
        },
        {
            name: "Miscellaneous",
            symbols: [
                { symbol: "‰", name: "per mille" },
                { symbol: "′", name: "prime" },
                { symbol: "″", name: "double prime" },
                { symbol: "ℕ", name: "naturals" },
                { symbol: "ℤ", name: "integers" },
                { symbol: "ℚ", name: "rationals" },
                { symbol: "ℝ", name: "reals" },
                { symbol: "ℂ", name: "complex" },
            ],
        },
    ],
};
